version: 0.2
       
phases:
  install:
    commands:
      - echo "Get EKS cluster version"
      - CLUSTER_VERSION=`aws eks describe-cluster --name ${EKS_CLUSTER_NAME} | jq -r .cluster.version`
      - KUBECTL_VERSION=${CLUSTER_VERSION}.0-00
      - echo "Installing required tools"
      - npm install
      - apt-get update
      - apt-get install -y apt-transport-https ca-certificates curl
      - curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg
      - echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | tee /etc/apt/sources.list.d/kubernetes.list
      - apt-get update && apt-get install -y kubectl=${KUBECTL_VERSION} jq gettext-base
      - echo "Updating kubeconfig file"
      - aws eks update-kubeconfig --name ${EKS_CLUSTER_NAME}
  build:
    commands:
      - echo "Building docker image and pushing to ECR"
      - aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin ${ECR_REGISTRY}
      - make build
      - docker tag task-list-frontend:latest ${ECR_REPOSITORY_URI}:${CODEBUILD_RESOLVED_SOURCE_VERSION}
      - docker push ${ECR_REPOSITORY_URI}:${CODEBUILD_RESOLVED_SOURCE_VERSION}
  post_build:
    commands:
      - echo "Deploying manifest file"
      - envsubst < deploy/config/manifest.yaml | kubectl apply -f -
